name: Landing CI Pipeline

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/landing/**'
      - '.github/workflows/landing-ci.yml'
      - 'package.json'
      - 'bun.lockb'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/landing/**'
      - '.github/workflows/landing-ci.yml'
      - 'package.json'
      - 'bun.lockb'

jobs:
  # Job 1: Install dependencies and cache
  setup:
    name: Setup Dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Generate cache key
        id: cache-key
        run: echo "key=bun-${{ hashFiles('**/bun.lockb', '**/package.json') }}" >> $GITHUB_OUTPUT

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        id: bun-cache
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            apps/landing/node_modules
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            bun-${{ hashFiles('**/bun.lockb') }}
            bun-

      - name: Install dependencies
        if: steps.bun-cache.outputs.cache-hit != 'true'
        run: bun install --frozen-lockfile

  # Job 2: Linting
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore Bun cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            apps/landing/node_modules
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Install dependencies (if cache miss)
        run: bun install --frozen-lockfile

      - name: Run ESLint on landing
        run: |
          # Check if landing has its own package.json, otherwise run from root
          if [ -f "apps/landing/package.json" ]; then
            cd apps/landing
            bun run lint
          else
            # Run ESLint on landing directory from root
            bunx eslint apps/landing --ext .js,.jsx,.ts,.tsx
          fi
        continue-on-error: false

  # Job 3: Type checking
  typecheck:
    name: TypeScript Check
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore Bun cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            apps/landing/node_modules
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Install dependencies (if cache miss)
        run: bun install --frozen-lockfile

      - name: Run TypeScript check
        run: |
          # Check if landing has its own tsconfig, otherwise use root
          if [ -f "apps/landing/tsconfig.json" ]; then
            cd apps/landing
            bun run type-check || npx tsc --noEmit
          else
            # Run TypeScript check from root
            npx tsc --noEmit --project . --include "apps/landing/**/*"
          fi

  # Job 4: Build test
  build:
    name: Build Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore Bun cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            apps/landing/node_modules
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Install dependencies (if cache miss)
        run: bun install --frozen-lockfile

      - name: Build landing page
        run: |
          # Check if landing has its own build script, otherwise build from root
          if [ -f "apps/landing/package.json" ] && grep -q '"build"' apps/landing/package.json; then
            cd apps/landing
            bun run build
          else
            # Build from root (assuming Next.js app structure)
            bun run build
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: landing-build
          path: |
            .next/
            apps/landing/.next/
          retention-days: 1

  # Job 5: Basic SEO Tests (without deployment)
  seo-tests:
    name: SEO & Performance Tests
    runs-on: ubuntu-latest
    needs: [setup, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore Bun cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            apps/landing/node_modules
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Install dependencies (if cache miss)
        run: bun install --frozen-lockfile

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: landing-build
          path: ./

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.12.x

      - name: Start Next.js server and run Lighthouse
        run: |
          # Start the server
          bun run start &
          sleep 15
          # Test the landing page route
          lhci autorun --config='{"ci":{"collect":{"url":["http://localhost:3000/landing"],"numberOfRuns":1},"assert":{"assertions":{"categories:performance":["warn",{"minScore":0.7}],"categories:accessibility":["error",{"minScore":0.9}],"categories:seo":["error",{"minScore":0.9}]}}}}'
        env:
          PORT: 3000

  # Job 6: Unit Tests (if test script exists)
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Restore Bun cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            apps/landing/node_modules
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Install dependencies (if cache miss)
        run: bun install --frozen-lockfile

      - name: Check if test script exists
        id: check-tests
        run: |
          if [ -f "apps/landing/package.json" ] && grep -q '"test"' apps/landing/package.json; then
            echo "has-tests=true" >> $GITHUB_OUTPUT
            echo "test-location=landing" >> $GITHUB_OUTPUT
          elif grep -q '"test"' package.json; then
            echo "has-tests=true" >> $GITHUB_OUTPUT
            echo "test-location=root" >> $GITHUB_OUTPUT
          else
            echo "has-tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Run tests from landing directory
        if: steps.check-tests.outputs.has-tests == 'true' && steps.check-tests.outputs.test-location == 'landing'
        run: |
          cd apps/landing
          bun run test

      - name: Run tests from root (landing specific)
        if: steps.check-tests.outputs.has-tests == 'true' && steps.check-tests.outputs.test-location == 'root'
        run: |
          # Run tests that match landing directory
          bun run test -- apps/landing || echo "No landing-specific tests found"

  # Summary job
  ci-summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [lint, typecheck, build, seo-tests]
    if: always()
    steps:
      - name: Check results
        run: |
          echo "🚀 Landing CI Pipeline Results:"
          echo "✅ Linting: ${{ needs.lint.result }}"
          echo "✅ Type Check: ${{ needs.typecheck.result }}"
          echo "✅ Build: ${{ needs.build.result }}"
          echo "✅ SEO Tests: ${{ needs.seo-tests.result }}"
          
          if [[ "${{ needs.lint.result }}" == "success" && "${{ needs.typecheck.result }}" == "success" && "${{ needs.build.result }}" == "success" && "${{ needs.seo-tests.result }}" == "success" ]]; then
            echo "🎉 All checks passed! Landing page is ready."
          else
            echo "❌ Some checks failed. Please review the logs above."
            exit 1
          fi
